auto:
  name: ğŸ¤– Avtomatik
  welcome_message: ğŸ¤– Salom, men <b>Gemini AI</b> botman. Nimani yaratmoqchisiz?
  parse_mode: html


manual:
  name: ğŸ‘©ğŸ¼â€ğŸ’» Qo'lda
  welcome_message: ğŸ‘©ğŸ¼â€ğŸ’» Nimani yaratmoqchisiz?
  parse_mode: html
